apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - {{ .Values.accessModes }}
  hostPath:
    path: {{ .Values.hostPath }}

