apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldbclaim
spec:
  accessModes:
    - {{ .Values.accessModes }}
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
